# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_calibration_line.ui',
# licensing of 'set_calibration_line.ui' applies.
#
# Created: Wed Oct 16 16:30:45 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(891, 755)
        self.pushButton_check = QtWidgets.QPushButton(Form)
        self.pushButton_check.setGeometry(QtCore.QRect(60, 540, 205, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_check.sizePolicy().hasHeightForWidth())
        self.pushButton_check.setSizePolicy(sizePolicy)
        self.pushButton_check.setMinimumSize(QtCore.QSize(205, 50))
        self.pushButton_check.setMaximumSize(QtCore.QSize(205, 50))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        self.pushButton_check.setFont(font)
        self.pushButton_check.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_check.setObjectName("pushButton_check")
        self.pushButton_submit = QtWidgets.QPushButton(Form)
        self.pushButton_submit.setGeometry(QtCore.QRect(60, 640, 205, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_submit.sizePolicy().hasHeightForWidth())
        self.pushButton_submit.setSizePolicy(sizePolicy)
        self.pushButton_submit.setMinimumSize(QtCore.QSize(205, 50))
        self.pushButton_submit.setMaximumSize(QtCore.QSize(205, 50))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 30, 411, 481))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 43, 386, 424))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_Axis = QtWidgets.QLabel(self.widget)
        self.label_Axis.setMinimumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_Axis.setFont(font)
        self.label_Axis.setObjectName("label_Axis")
        self.horizontalLayout_9.addWidget(self.label_Axis)
        self.label_Axis_X = QtWidgets.QLabel(self.widget)
        self.label_Axis_X.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_Axis_X.setFont(font)
        self.label_Axis_X.setObjectName("label_Axis_X")
        self.horizontalLayout_9.addWidget(self.label_Axis_X)
        self.label_Axis_Y = QtWidgets.QLabel(self.widget)
        self.label_Axis_Y.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_Axis_Y.setFont(font)
        self.label_Axis_Y.setObjectName("label_Axis_Y")
        self.horizontalLayout_9.addWidget(self.label_Axis_Y)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_ = QtWidgets.QLabel(self.widget)
        self.label_.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_.setFont(font)
        self.label_.setObjectName("label_")
        self.horizontalLayout.addWidget(self.label_)
        self.spinBox_ptStart_bottom_x = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptStart_bottom_x.sizePolicy().hasHeightForWidth())
        self.spinBox_ptStart_bottom_x.setSizePolicy(sizePolicy)
        self.spinBox_ptStart_bottom_x.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptStart_bottom_x.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptStart_bottom_x.setFont(font)
        self.spinBox_ptStart_bottom_x.setMaximum(2048)
        self.spinBox_ptStart_bottom_x.setSingleStep(1)
        self.spinBox_ptStart_bottom_x.setObjectName("spinBox_ptStart_bottom_x")
        self.horizontalLayout.addWidget(self.spinBox_ptStart_bottom_x)
        self.spinBox_ptStart_bottom_y = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptStart_bottom_y.sizePolicy().hasHeightForWidth())
        self.spinBox_ptStart_bottom_y.setSizePolicy(sizePolicy)
        self.spinBox_ptStart_bottom_y.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptStart_bottom_y.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptStart_bottom_y.setFont(font)
        self.spinBox_ptStart_bottom_y.setMaximum(2048)
        self.spinBox_ptStart_bottom_y.setSingleStep(1)
        self.spinBox_ptStart_bottom_y.setObjectName("spinBox_ptStart_bottom_y")
        self.horizontalLayout.addWidget(self.spinBox_ptStart_bottom_y)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_ptEnd_bottom_x = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptEnd_bottom_x.sizePolicy().hasHeightForWidth())
        self.spinBox_ptEnd_bottom_x.setSizePolicy(sizePolicy)
        self.spinBox_ptEnd_bottom_x.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptEnd_bottom_x.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptEnd_bottom_x.setFont(font)
        self.spinBox_ptEnd_bottom_x.setMaximum(2048)
        self.spinBox_ptEnd_bottom_x.setObjectName("spinBox_ptEnd_bottom_x")
        self.horizontalLayout_2.addWidget(self.spinBox_ptEnd_bottom_x)
        self.spinBox_ptEnd_bottom_y = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptEnd_bottom_y.sizePolicy().hasHeightForWidth())
        self.spinBox_ptEnd_bottom_y.setSizePolicy(sizePolicy)
        self.spinBox_ptEnd_bottom_y.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptEnd_bottom_y.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptEnd_bottom_y.setFont(font)
        self.spinBox_ptEnd_bottom_y.setMaximum(2048)
        self.spinBox_ptEnd_bottom_y.setObjectName("spinBox_ptEnd_bottom_y")
        self.horizontalLayout_2.addWidget(self.spinBox_ptEnd_bottom_y)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_ptStart_top_x = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptStart_top_x.sizePolicy().hasHeightForWidth())
        self.spinBox_ptStart_top_x.setSizePolicy(sizePolicy)
        self.spinBox_ptStart_top_x.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptStart_top_x.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptStart_top_x.setFont(font)
        self.spinBox_ptStart_top_x.setMaximum(2048)
        self.spinBox_ptStart_top_x.setObjectName("spinBox_ptStart_top_x")
        self.horizontalLayout_3.addWidget(self.spinBox_ptStart_top_x)
        self.spinBox_ptStart_top_y = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptStart_top_y.sizePolicy().hasHeightForWidth())
        self.spinBox_ptStart_top_y.setSizePolicy(sizePolicy)
        self.spinBox_ptStart_top_y.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptStart_top_y.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptStart_top_y.setFont(font)
        self.spinBox_ptStart_top_y.setMaximum(2048)
        self.spinBox_ptStart_top_y.setObjectName("spinBox_ptStart_top_y")
        self.horizontalLayout_3.addWidget(self.spinBox_ptStart_top_y)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_ptEnd_top_x = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptEnd_top_x.sizePolicy().hasHeightForWidth())
        self.spinBox_ptEnd_top_x.setSizePolicy(sizePolicy)
        self.spinBox_ptEnd_top_x.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptEnd_top_x.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptEnd_top_x.setFont(font)
        self.spinBox_ptEnd_top_x.setMaximum(2048)
        self.spinBox_ptEnd_top_x.setObjectName("spinBox_ptEnd_top_x")
        self.horizontalLayout_4.addWidget(self.spinBox_ptEnd_top_x)
        self.spinBox_ptEnd_top_y = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_ptEnd_top_y.sizePolicy().hasHeightForWidth())
        self.spinBox_ptEnd_top_y.setSizePolicy(sizePolicy)
        self.spinBox_ptEnd_top_y.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_ptEnd_top_y.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_ptEnd_top_y.setFont(font)
        self.spinBox_ptEnd_top_y.setMaximum(2048)
        self.spinBox_ptEnd_top_y.setObjectName("spinBox_ptEnd_top_y")
        self.horizontalLayout_4.addWidget(self.spinBox_ptEnd_top_y)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_marble_line_start = QtWidgets.QLabel(self.widget)
        self.label_marble_line_start.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_marble_line_start.setFont(font)
        self.label_marble_line_start.setObjectName("label_marble_line_start")
        self.horizontalLayout_5.addWidget(self.label_marble_line_start)
        self.spinBox_pts_vertical_start_x = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_start_x.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_start_x.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_start_x.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_start_x.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_start_x.setFont(font)
        self.spinBox_pts_vertical_start_x.setMaximum(2048)
        self.spinBox_pts_vertical_start_x.setObjectName("spinBox_pts_vertical_start_x")
        self.horizontalLayout_5.addWidget(self.spinBox_pts_vertical_start_x)
        self.spinBox_pts_vertical_start_y = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_start_y.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_start_y.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_start_y.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_start_y.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_start_y.setFont(font)
        self.spinBox_pts_vertical_start_y.setMaximum(2048)
        self.spinBox_pts_vertical_start_y.setObjectName("spinBox_pts_vertical_start_y")
        self.horizontalLayout_5.addWidget(self.spinBox_pts_vertical_start_y)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_marble_line_end = QtWidgets.QLabel(self.widget)
        self.label_marble_line_end.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_marble_line_end.setFont(font)
        self.label_marble_line_end.setObjectName("label_marble_line_end")
        self.horizontalLayout_6.addWidget(self.label_marble_line_end)
        self.spinBox_pts_vertical_end_x = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_end_x.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_end_x.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_end_x.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_end_x.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_end_x.setFont(font)
        self.spinBox_pts_vertical_end_x.setMaximum(2048)
        self.spinBox_pts_vertical_end_x.setObjectName("spinBox_pts_vertical_end_x")
        self.horizontalLayout_6.addWidget(self.spinBox_pts_vertical_end_x)
        self.spinBox_pts_vertical_end_y = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_end_y.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_end_y.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_end_y.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_end_y.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_end_y.setFont(font)
        self.spinBox_pts_vertical_end_y.setMaximum(2048)
        self.spinBox_pts_vertical_end_y.setObjectName("spinBox_pts_vertical_end_y")
        self.horizontalLayout_6.addWidget(self.spinBox_pts_vertical_end_y)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_marble_line_start_right = QtWidgets.QLabel(self.widget)
        self.label_marble_line_start_right.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_marble_line_start_right.setFont(font)
        self.label_marble_line_start_right.setObjectName("label_marble_line_start_right")
        self.horizontalLayout_10.addWidget(self.label_marble_line_start_right)
        self.spinBox_pts_vertical_start_x_right = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_start_x_right.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_start_x_right.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_start_x_right.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_start_x_right.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_start_x_right.setFont(font)
        self.spinBox_pts_vertical_start_x_right.setMaximum(2048)
        self.spinBox_pts_vertical_start_x_right.setObjectName("spinBox_pts_vertical_start_x_right")
        self.horizontalLayout_10.addWidget(self.spinBox_pts_vertical_start_x_right)
        self.spinBox_pts_vertical_start_y_right = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_start_y_right.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_start_y_right.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_start_y_right.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_start_y_right.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_start_y_right.setFont(font)
        self.spinBox_pts_vertical_start_y_right.setMaximum(2048)
        self.spinBox_pts_vertical_start_y_right.setObjectName("spinBox_pts_vertical_start_y_right")
        self.horizontalLayout_10.addWidget(self.spinBox_pts_vertical_start_y_right)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_marble_line_end_right = QtWidgets.QLabel(self.widget)
        self.label_marble_line_end_right.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_marble_line_end_right.setFont(font)
        self.label_marble_line_end_right.setObjectName("label_marble_line_end_right")
        self.horizontalLayout_8.addWidget(self.label_marble_line_end_right)
        self.spinBox_pts_vertical_end_x_right = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_end_x_right.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_end_x_right.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_end_x_right.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_end_x_right.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_end_x_right.setFont(font)
        self.spinBox_pts_vertical_end_x_right.setMaximum(2048)
        self.spinBox_pts_vertical_end_x_right.setObjectName("spinBox_pts_vertical_end_x_right")
        self.horizontalLayout_8.addWidget(self.spinBox_pts_vertical_end_x_right)
        self.spinBox_pts_vertical_end_y_right = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_end_y_right.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_end_y_right.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_end_y_right.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_end_y_right.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_end_y_right.setFont(font)
        self.spinBox_pts_vertical_end_y_right.setMaximum(2048)
        self.spinBox_pts_vertical_end_y_right.setObjectName("spinBox_pts_vertical_end_y_right")
        self.horizontalLayout_8.addWidget(self.spinBox_pts_vertical_end_y_right)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.spinBox_pts_vertical_interval = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_interval.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_interval.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_interval.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_interval.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_interval.setFont(font)
        self.spinBox_pts_vertical_interval.setMaximum(2048)
        self.spinBox_pts_vertical_interval.setObjectName("spinBox_pts_vertical_interval")
        self.horizontalLayout_7.addWidget(self.spinBox_pts_vertical_interval)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_marble_interval_right = QtWidgets.QLabel(self.widget)
        self.label_marble_interval_right.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_marble_interval_right.setFont(font)
        self.label_marble_interval_right.setObjectName("label_marble_interval_right")
        self.horizontalLayout_11.addWidget(self.label_marble_interval_right)
        self.spinBox_pts_vertical_interval_right = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_pts_vertical_interval_right.sizePolicy().hasHeightForWidth())
        self.spinBox_pts_vertical_interval_right.setSizePolicy(sizePolicy)
        self.spinBox_pts_vertical_interval_right.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_pts_vertical_interval_right.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_pts_vertical_interval_right.setFont(font)
        self.spinBox_pts_vertical_interval_right.setMaximum(2048)
        self.spinBox_pts_vertical_interval_right.setObjectName("spinBox_pts_vertical_interval_right")
        self.horizontalLayout_11.addWidget(self.spinBox_pts_vertical_interval_right)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 30, 271, 131))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 246, 73))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.spinBox_min_threshold = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_min_threshold.sizePolicy().hasHeightForWidth())
        self.spinBox_min_threshold.setSizePolicy(sizePolicy)
        self.spinBox_min_threshold.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_min_threshold.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_min_threshold.setFont(font)
        self.spinBox_min_threshold.setMaximum(255)
        self.spinBox_min_threshold.setSingleStep(1)
        self.spinBox_min_threshold.setObjectName("spinBox_min_threshold")
        self.horizontalLayout_28.addWidget(self.spinBox_min_threshold)
        self.gridLayout_4.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        self.spinBox_max_threshold = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.spinBox_max_threshold.sizePolicy().hasHeightForWidth())
        self.spinBox_max_threshold.setSizePolicy(sizePolicy)
        self.spinBox_max_threshold.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBox_max_threshold.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinBox_max_threshold.setFont(font)
        self.spinBox_max_threshold.setMaximum(255)
        self.spinBox_max_threshold.setSingleStep(1)
        self.spinBox_max_threshold.setObjectName("spinBox_max_threshold")
        self.horizontalLayout_29.addWidget(self.spinBox_max_threshold)
        self.gridLayout_4.addLayout(self.horizontalLayout_29, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_check, QtCore.SIGNAL("clicked()"), Form.check)
        QtCore.QObject.connect(self.pushButton_submit, QtCore.SIGNAL("clicked()"), Form.submit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "设置标定线", None, -1))
        self.pushButton_check.setText(QtWidgets.QApplication.translate("Form", "查看", None, -1))
        self.pushButton_submit.setText(QtWidgets.QApplication.translate("Form", "保存退出", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "校准线设置", None, -1))
        self.label_Axis.setText(QtWidgets.QApplication.translate("Form", "坐标轴:   ", None, -1))
        self.label_Axis_X.setText(QtWidgets.QApplication.translate("Form", "X轴:", None, -1))
        self.label_Axis_Y.setText(QtWidgets.QApplication.translate("Form", "Y轴:", None, -1))
        self.label_.setText(QtWidgets.QApplication.translate("Form", "底线起点:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "底线终点:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "顶线起点:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "顶线终点:", None, -1))
        self.label_marble_line_start.setText(QtWidgets.QApplication.translate("Form", "左弹子线起点:", None, -1))
        self.label_marble_line_end.setText(QtWidgets.QApplication.translate("Form", "左弹子线终点:", None, -1))
        self.label_marble_line_start_right.setText(QtWidgets.QApplication.translate("Form", "右弹子线起点:", None, -1))
        self.label_marble_line_end_right.setText(QtWidgets.QApplication.translate("Form", "右弹子线终点:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "左弹子线间距:", None, -1))
        self.label_marble_interval_right.setText(QtWidgets.QApplication.translate("Form", "右弹子线间距:", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "边缘检测参数", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("Form", "阈值下限：", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Form", "阈值上限：", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

